#spring.profiles.active: local
server:
  port: 8091
  ssl:
    enabled: false # Uses self-signed certificate because no key-store configuration is specified.

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    au.com.mebank.service: DEBUG
    au.com.mebank.service.handler: DEBUG

cxf:
  path: /service